import http from 'k6/http';
import { check, sleep } from 'k6';

export let options = {
  stages: [
    { duration: '10s', target: 20 },  // Ramp-up to 20 users
    { duration: '30s', target: 50 },  // Stay at 50 users
    { duration: '10s', target: 100 }, // Peak at 100 users
    { duration: '10s', target: 0 },   // Ramp-down to 0
  ],
  thresholds: {
    http_req_duration: ['p(95)<2000'], // 95% of requests should be below 2s
    http_req_failed: ['rate<0.1'],     // Error rate should be less than 10%
  },
};

const USER_SERVICE_URL = 'http://user-service.staging.svc.cluster.local:8001';
const TODO_SERVICE_URL = 'http://todo-service.staging.svc.cluster.local:8002';

// Setup function - runs once before test starts
export function setup() {
  const username = `loadtest_${Date.now()}`;
  const email = `loadtest_${Date.now()}@test.com`;
  const password = 'TestPassword123!';

  // Register a new user
  const registerPayload = JSON.stringify({
    username: username,
    email: email,
    password: password,
  });

  const registerRes = http.post(`${USER_SERVICE_URL}/register`, registerPayload, {
    headers: { 'Content-Type': 'application/json' },
  });

  if (registerRes.status !== 200) {
    console.error('Failed to register user:', registerRes.status, registerRes.body);
    // If registration fails, maybe user exists, try to login anyway
  }

  // Login to get JWT token
  const loginPayload = JSON.stringify({
    username: username,
    password: password,
  });

  const loginRes = http.post(`${USER_SERVICE_URL}/login`, loginPayload, {
    headers: { 'Content-Type': 'application/json' },
  });

  if (loginRes.status !== 200) {
    console.error('Failed to login:', loginRes.status, loginRes.body);
    throw new Error('Setup failed: Unable to get JWT token');
  }

  const token = JSON.parse(loginRes.body).access_token;
  console.log('Setup complete: Got JWT token');
  
  return { token: token };
}

export default function (data) {
  const token = data.token;
  const authHeaders = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
  };

  // Test GET /ready endpoint (no auth required)
  let res1 = http.get(`${TODO_SERVICE_URL}/ready`);
  check(res1, {
    'GET /ready status is 200': (r) => r.status === 200,
  });

  // Test GET /todos endpoint (with auth)
  let res2 = http.get(`${TODO_SERVICE_URL}/todos`, authHeaders);
  check(res2, {
    'GET /todos status is 200': (r) => r.status === 200,
  });
  
  // Test POST /todos endpoint (with auth)
  let payload = JSON.stringify({
    title: `Load Test Task - ${Date.now()}`,
    description: 'Generated by k6 load test',
  });
  
  let res3 = http.post(`${TODO_SERVICE_URL}/todos`, payload, authHeaders);
  check(res3, {
    'POST /todos status is 200': (r) => r.status === 200,
  });
  
  sleep(0.1); // Small delay between iterations
}

