apiVersion: v1
kind: Service
metadata:
  name: argocd-loadbalancer
  namespace: argocd
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.112  # Sabit IP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server