apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-cache-pvc
  namespace: jenkins # Jenkins'in çalıştığı namespace
spec:
  accessModes:
    - ReadWriteOnce # Tek bir node tarafından okunup yazılabilir
  resources:
    requests:
      storage: 10Gi # Docker imajları için cömert bir alan, ihtiyaca göre ayarlayın
