apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.100.203"],"port":443,"protocol":"HTTPS","serviceName":"nextcloud:nextcloud","ingressName":"nextcloud:nextcloud-https-ingress","hostname":"nextcloud.ne-inc.com","path":"/","allNodes":false}]'
    meta.helm.sh/release-name: nextcloud
    meta.helm.sh/release-namespace: nextcloud
  creationTimestamp: "2025-03-31T19:01:04Z"
  generation: 2
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/version: 30.0.6
    helm.sh/chart: nextcloud-6.6.9
  name: nextcloud
  namespace: nextcloud
  resourceVersion: "152870"
  uid: 7324080c-8c79-4aa4-97b2-3d8a7e96ee31
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/name: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        hooks-hash: 9525c2748a6c7cd0e28ec740623d0b3fa5a75c83b51ccfd136bc89c76737b204
        nextcloud-config-hash: 8266a725d5474acb6adbf9f0609a3494dc3340a3ac306db90eac9ddb1b851960
        php-config-hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: db-username
              name: nextcloud-db
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: nextcloud-db
        - name: MYSQL_HOST
          value: nextcloud-mariadb
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: nextcloud-username
              name: nextcloud
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: nextcloud-password
              name: nextcloud
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.kube.home
        - name: NEXTCLOUD_DATA_DIR
          value: /var/www/html/data
        image: nextcloud:30.0.6-apache
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: nextcloud.kube.home
            path: /status.php
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: nextcloud
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: nextcloud.kube.home
            path: /status.php
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/
          name: nextcloud-main
          subPath: root
        - mountPath: /var/www/html
          name: nextcloud-main
          subPath: html
        - mountPath: /var/www/html/data
          name: nextcloud-data
          subPath: data
        - mountPath: /var/www/html/config
          name: nextcloud-config
          subPath: config
        - mountPath: /var/www/html/custom_apps
          name: nextcloud-custom-apps
          subPath: custom_apps
        - mountPath: /var/www/tmp
          name: nextcloud-tmp
          subPath: tmp
        - mountPath: /var/www/html/themes
          name: nextcloud-themes
          subPath: themes
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until mysql --host=nextcloud-mariadb --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute="SELECT 1;"; do echo waiting for mysql; sleep 2; done;
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: db-username
              name: nextcloud-db
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: nextcloud-db
        image: docker.io/bitnami/mariadb:11.3.2-debian-12-r5
        imagePullPolicy: IfNotPresent
        name: mariadb-isalive
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 33
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nextcloud-main
        emptyDir: {}
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc
      - name: nextcloud-config
        persistentVolumeClaim:
          claimName: nextcloud-config-pvc
      - name: nextcloud-custom-apps
        emptyDir: {}
      - name: nextcloud-tmp
        emptyDir: {}
      - name: nextcloud-themes
        emptyDir: {}
