apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.database.name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.database.env.username | b64enc | quote }}
  password: {{ .Values.database.env.password | b64enc | quote }}
  database: {{ .Values.database.env.database | b64enc | quote }}
  # Construct the connection string: postgresql://user:pass@host:port/db
  database-url: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.database.env.username .Values.database.env.password .Values.database.name (int .Values.database.service.port) .Values.database.env.database | b64enc | quote }}
